services:
  - type: web
    name: bidsphere-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRY
        value: 7d
      - key: ADMIN_EMAIL
        value: shivampatel9189@gmail.com
      - key: ADMIN_PASSWORD
        value: Admin@123
      - key: ADMIN_IP
        value: ""
      - key: SMTP_USER
        value: shivampatel9189@gmail.com
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_PASS
        value: jptosjfozmtocjbu
      - key: SHIPROCKET_EMAIL
        value: ""
      - key: SHIPROCKET_PASSWORD
        value: ""
      - key: CLIENT_ORIGIN
        value: https://bidsphere-online-auction-system.vercel.app
      - key: EMAIL_USER
        value: shivampatel9189@gmail.com
      - key: EMAIL_PASS
        value: jptosjfozmtocjbu
      - key: CLOUDINARY_URL
        value: cloudinary://936615288422435:Y4DaNOWo1v2dNFbHXbq5MDHYrq4@l9nrfyhf
      - key: CLOUDINARY_CLOUD_NAME
        value: l9nrfyhf
      - key: CLOUDINARY_API_KEY
        value: "936615288422435"
      - key: CLOUDINARY_API_SECRET
        value: Y4DaNOWo1v2dNFbHXbq5MDHYrq4
      - key: NODE_VERSION
        value: 20
      - key: AUCTION_STATUS_UPDATER_CRON
        value: "*/1 * * * *"
